---
- name: Install PHP Package.(CentOS or RedHat)
  package:
    name: "{{ php_install_package }}"
    state: "present"
    enablerepo: "{{ php_enable_repo | default(omit, true) }}"
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install PHP Package.(Fedora)
  package:
    name: "{{ php_install_package }}"
    state: "present"
  when: ansible_distribution == "Fedora" or ansible_distribution == "Ubuntu"

- name: Install extra package.
  package:
    name: "{{ php_packages_extra }}"
    state: "present"
  when: php_packages_extra is defined
